services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    env_file:
      - .env
  
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
    - ../backend:/app        # Mapeia o código fonte local para dentro do container
    - /app/node_modules      # Garante que node_modules do container não seja sobrescrito
  
volumes:
  postgres_data:
  pgadmin_data:


